/**
 * 受控 ABAP 执行 API（矩阵行 devtools.execute-abap 的执行核；VSP 来源
 * pkg/adt/workflows_execute.go ExecuteABAP 语义移植）。
 *
 * 机制：把用户代码包进一个一次性 ABAP Unit 测试包装程序（wrapper report），
 * 激活后 RunUnitTests 单次运行；包装方法以 cl_abap_unit_assert=>fail 收尾，
 * 断言消息携带 "EXEC_RESULT:" 前缀把值带出测试沙箱——这是值离开测试方法的
 * 唯一通道。运行后临时程序即删除（除非调用方要求保留）。
 *
 * 失败语义（VSP 移植）：
 * - 语法错误在激活步即被 200 内的编译失败捕获（ABAP Unit 对未生成的程序
 *   应答空 runResult，"空"不等于"通过"）；
 * - notRun：激活成功但 ABAP Unit 没有任何测试类——代码无法被证明运行过；
 * - PayloadFailure：用户代码中途死亡（exception/critical），行号回译到
 *   用户代码（包装器行号对提交者无意义）。
 */
import type { AdtHTTP } from './AdtHTTP.js'
import { createObject } from './api/objectcreator.js'
import type { NewObjectOptions } from './api/objectcreator.js'
import { lock, unLock, setObjectSource } from './api/objectcontents.js'
import { activate } from './api/activate.js'
import { deleteObject } from './api/delete.js'
import { runUnitTest } from './api/unittest.js'
import type { UnitTestRunFlags, UnitTestAlert, UnitTestClass } from './api/unittest.js'
export type { UnitTestAlert, UnitTestClass }

export interface ExecuteAbapOptions {
  /** 声明代码会做什么：harmless（默认，无 DB 写）/ dangerous / critical。 */
  riskLevel?: string
  returnVariable?: string
  keepProgram?: boolean
  programPrefix?: string
}

export interface ExecuteFailure {
  kind: string
  severity?: string
  title: string
  details?: string[]
}



export interface ExecuteUnitTestClasses {
  alerts: UnitTestAlert[]
  testmethods?: Array<{ executionTime?: number; alerts?: UnitTestAlert[] }>
}

export interface ExecuteAbapResult {
  success: boolean
  programName: string
  /** EXEC_RESULT 断言消息携带出的输出值（按产出顺序）。 */
  output: string[]
  /** 全部 alert 明细（调试用，ABAP Unit 原生形态）。 */
  rawAlerts: UnitTestAlert[]
  /** 执行耗时（秒，ABAP Unit 汇总）。 */
  executionTime: number
  message: string
  /** 临时程序是否已删除（keepProgram=true 或清理失败时为 false）。 */
  cleanedUp: boolean
  /** 清理阶段警告（不改变 success 语义）。 */
  cleanupWarnings: string[]
  failure?: ExecuteFailure
}

export const EXEC_RESULT_MARKER = 'EXEC_RESULT:'
export const PAYLOAD_START_MARKER = '" === USER CODE START ==='

const DEFAULT_PROGRAM_PREFIX = 'ZTEMP_EXEC_'
const DEFAULT_SYMBOL_MAX_LENGTH = 132

function upper(text: string): string {
  return text.trim().toUpperCase()
}

/** ABAP 源的行切分（\r\n 归一化）。 */
export function splitLines(source: string): string[] {
  return source.replace(/\r\n/g, '\n').split('\n')
}

/** ABAP 注释行（"*" 全行注释与 '"' 半行注释起始）。 */
export function isCommentLine(line: string): boolean {
  const trimmed = line.trim()
  return trimmed.startsWith('*') || trimmed.startsWith('"')
}

/**
 * ABAP 变量名合法性（字母/下划线开头，30 位上限）——returnVariable 会被
 * 直接拼进 wrapper 模板与字符串模板，非法字符必须在任何 SAP 调用之前拒绝。
 */
export function isValidAbapVariableName(name: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]{0,29}$/.test(name)
}

/** riskLevel 字符串到 ABAP RISK LEVEL 子句。 */
export function riskLevelABAP(riskLevel: string): string {
  switch (riskLevel.toLowerCase()) {
    case 'dangerous': return 'RISK LEVEL DANGEROUS'
    case 'critical': return 'RISK LEVEL CRITICAL'
    default: return 'RISK LEVEL HARMLESS'
  }
}

/** RunUnitTests flags 由 riskLevel 推导（harmless 默认；dangerous 含 harmless；critical 全开）。 */
export function unitTestFlagsFor(riskLevel: string): UnitTestRunFlags {
  const lower = riskLevel.toLowerCase()
  return {
    harmless: true,
    dangerous: lower === 'dangerous' || lower === 'critical',
    critical: lower === 'critical',
    short: true,
    medium: true,
    long: false
  }
}

/**
 * 包装器模板（VSP executeWrapperSource 移植）：用户代码嵌在
 * PAYLOAD_START_MARKER 与 USER CODE END 之间；MARKER 行用于行号回译。
 */
export function executeWrapperSource(
  programName: string,
  riskLevelABAPClause: string,
  returnVariable: string,
  code: string
): string {
  return `REPORT ${programName}.

*&---------------------------------------------------------------------*
*& Auto-generated program for code execution via unit test
*& Generated by ExecuteAbap workflow
*&---------------------------------------------------------------------*

CLASS ltc_executor DEFINITION FOR TESTING ${riskLevelABAPClause} DURATION SHORT.
  PUBLIC SECTION.
    METHODS execute_payload FOR TESTING.
ENDCLASS.

CLASS ltc_executor IMPLEMENTATION.
  METHOD execute_payload.
    DATA ${returnVariable} TYPE string.

    ${PAYLOAD_START_MARKER}
${code}
    " === USER CODE END ===

    " Return result via assertion message
    cl_abap_unit_assert=>fail( msg = |${EXEC_RESULT_MARKER}{ ${returnVariable} }| ).
  ENDMETHOD.
ENDCLASS.
`
}

/** 从 alert 文本提取 EXEC_RESULT 值（VSP execResult 移植：标记任意位置、尾引号归属 SAP 句子）。 */
export function execResult(text: string): { found: boolean; value: string } {
  const idx = text.indexOf(EXEC_RESULT_MARKER)
  if (idx < 0) return { found: false, value: '' }
  let value = text.slice(idx + EXEC_RESULT_MARKER.length)
  const before = text.slice(0, idx).trim()
  if (before.endsWith("'")) value = value.replace(/'$/, '')
  return { found: true, value }
}

/** 该 alert 是否为收尾断言（携带 EXEC_RESULT）而非失败。 */
export function carriesExecResult(alert: PayloadAlertInput): boolean {
  if (alert.title && execResult(alert.title).found) return true
  for (const d of alert.details ?? []) {
    if (execResult(d).found) return true
  }
  return false
}

/** payloadFailure 的宽松入参形态（测试与调用方均可提供普通对象）。 */
export interface PayloadAlertInput {
  kind?: string
  severity?: string
  title?: string
  details?: string[]
}

/** PayloadFailure：挑出"代码中途死亡"的 alert（exception 优先，critical/fatal 兜底）。 */
export function payloadFailure(alerts: PayloadAlertInput[]): PayloadAlertInput | undefined {
  let fallback: PayloadAlertInput | undefined
  for (const alert of alerts) {
    if (carriesExecResult(alert)) continue
    if (alert.kind?.toLowerCase() === 'exception') return alert
    if (!fallback && ['critical', 'fatal'].includes(alert.severity?.toLowerCase() ?? '')) fallback = alert
  }
  return fallback
}

/**
 * 编译失败提取：激活消息里定位本程序的 E/A 级错误（200 内拒绝，非异常路径）。
 * ADT ActivationResultMessage 的严重级在 `type` 字段（E/A/X/W/S），VSP 语义
 * 同款；`severity` 仅作宽松兼容（测试/其他来源）。
 */
export function compileFailureFromActivation(
  activation: { messages?: Array<{ severity?: string; type?: string; shortText?: string }> }
): ExecuteFailure | undefined {
  for (const message of activation.messages ?? []) {
    const severity = (message.severity ?? message.type ?? '').toUpperCase()
    if (['E', 'A'].includes(severity)) {
      return { kind: 'syntaxError', title: message.shortText ?? 'syntax error' }
    }
  }
  return undefined
}

/** 注入的 HTTP 通道（对齐项目既有 API 模块签名，全部为 AdtClient 既有公开能力）。 */
export interface ExecuteAbapHttp {
  /** 创建对象（NewObjectOptions 直传；不带 transport 即 $TMP 本地包）。 */
  create(options: NewObjectOptions): Promise<void>
  /** 对象锁（返回 LOCK_HANDLE）。 */
  lock(objectUrl: string, accessMode: string): Promise<{ LOCK_HANDLE?: string }>
  /** 全量源码写入（PUT /source/main，text/plain——真机 415 取证同款）。 */
  updateSource(objectSourceUrl: string, source: string, lockHandle: string, transport?: string): Promise<void>
  /** 解锁。 */
  unlock(objectUrl: string, lockHandle: string): Promise<unknown>
  /** 激活（返回激活消息集；ADT 原生形态严重级在 type 字段）。 */
  activate(objectUrl: string, objectName: string): Promise<{ messages?: Array<{ severity?: string; type?: string; shortText?: string }>; success?: boolean }>
  /** ABAP Unit 单次运行（返回 testClasses，alerts 含 title/details/severity）。 */
  runUnitTest(url: string, flags: UnitTestRunFlags): Promise<UnitTestClass[]>
  /** 对象删除。 */
  deleteObject(objectUrl: string, lockHandle: string, transport?: string): Promise<void>
}

/**
 * 执行用户代码（VSP ExecuteABAP 单次执行核移植）：
 * 创建临时程序 → 写包装器源 → 激活 → RunUnitTests → 提取 EXEC_RESULT →
 * 删除临时程序（keepProgram 除外）。任何中途失败都先尝试清理临时程序，
 * 清理失败如实记录（cleanupWarnings），不重试删除。
 */
export async function executeAbapViaUnitTest(
  h: ExecuteAbapHttp,
  code: string,
  opts: ExecuteAbapOptions = {}
): Promise<ExecuteAbapResult> {
  const riskLevel = opts.riskLevel || 'harmless'
  const returnVariable = opts.returnVariable || 'lv_result'
  const prefix = opts.programPrefix || DEFAULT_PROGRAM_PREFIX
  const keepProgram = opts.keepProgram === true

  const result: ExecuteAbapResult = {
    success: false, programName: '', output: [], rawAlerts: [],
    executionTime: 0, message: '', cleanedUp: false, cleanupWarnings: []
  }

  // 模板注入防线：变量名不合法直接拒绝，不触发任何 SAP 调用
  if (!isValidAbapVariableName(returnVariable)) {
    result.message = `Invalid return variable name: ${returnVariable}`
    return result
  }

  const timestamp = String(Date.now())
  const programName = upper(prefix + timestamp.slice(timestamp.length - 8))
  result.programName = programName
  const objectURL = `/sap/bc/adt/programs/programs/${programName.toLowerCase()}`

  const wrapperSource = executeWrapperSource(programName, riskLevelABAP(riskLevel), returnVariable, code)

  // 临时程序创建（CreateObject 不带 transport 即 $TMP 本地包）
  let created = false
  try {
    await h.create({
      objtype: 'PROG/P', name: programName, parentName: '$TMP',
      description: 'Temp program for ExecuteAbap', contentType: 'application/*'
    } as NewObjectOptions)
    created = true
  } catch (createError) {
    result.message = `Failed to create temp program: ${String(createError).slice(0, 200)}`
    return result
  }

  try {
    // 锁 + 写包装器源（PUT /source/main）。句柄键名宽松兼容（真机大写
    // LOCK_HANDLE，部分解析路径产出小写 lockHandle——DescriptionApi 同教训）。
    const lock = await h.lock(objectURL, 'MODIFY')
    const lockRecord = lock as { LOCK_HANDLE?: string; lockHandle?: string }
    const handle = String(lockRecord.LOCK_HANDLE ?? lockRecord.lockHandle ?? '')
    if (!handle) {
      result.message = 'Failed to lock temp program'
      return result
    }
    try {
      await h.updateSource(`${objectURL}/source/main`, wrapperSource, handle, '')
    } catch (writeError) {
      result.message = `Failed to update source: ${String(writeError).slice(0, 200)}`
      return result
    }
    await h.unlock(objectURL, handle)

    // 激活（编译失败在此暴露：200 内消息或 HTTP 异常都归为"代码未编译通过"，
    // VSP 语义——激活失败一律不进入运行步）
    let activation
    try {
      activation = await h.activate(objectURL, programName)
    } catch (activateError) {
      result.failure = { kind: 'syntaxError', title: String(activateError).slice(0, 200) }
      result.message = `The code did not compile: ${result.failure.title}`
      return result
    }
    const failure = compileFailureFromActivation(activation)
    if (failure) {
      result.failure = failure
      result.message = `The code did not compile: ${failure.title}`
      return result
    }

    // RunUnitTests（flags 由 riskLevel 推导）
    const classes = await h.runUnitTest(objectURL, unitTestFlagsFor(riskLevel))

    // EXEC_RESULT 提取 + RawAlerts 汇总 + 执行时间
    for (const cls of classes) {
      for (const method of cls.testmethods ?? []) {
        result.executionTime += method.executionTime ?? 0
        for (const alert of method.alerts ?? []) {
          result.rawAlerts.push(alert)
          const extracted = execResult(alert.title ?? '').found
            ? execResult(alert.title ?? '')
            : (alert.details ?? []).map((d: string) => execResult(d)).find((r: { found: boolean }) => r.found)
          if (extracted?.found) result.output.push(extracted.value)
        }
      }
      for (const alert of cls.alerts ?? []) {
        result.rawAlerts.push(alert)
        const extracted = execResult(alert.title ?? '').found
          ? execResult(alert.title ?? '')
          : (alert.details ?? []).map((d: string) => execResult(d)).find((r: { found: boolean }) => r.found)
        if (extracted?.found) result.output.push(extracted.value)
      }
    }

    // ABAP Unit 零测试类 = notRun（无法证明代码运行过，"空"不是"通过"）
    if (classes.length === 0) {
      result.failure = {
        kind: 'notRun',
        title: 'ABAP Unit reported no test at all, so the code cannot be shown to have run'
      }
      result.message = 'The code did not finish: ABAP Unit reported no test at all'
      return result
    }

    const payload = payloadFailure(result.rawAlerts)
    if (payload) {
      result.failure = {
        kind: payload.kind ?? 'exception',
        ...(payload.severity ? { severity: payload.severity } : {}),
        title: payload.title ?? 'runtime failure',
        ...(payload.details?.length ? { details: payload.details } : {})
      }
    }

    result.success = !result.failure
    result.message = result.failure
      ? `The code did not finish: ${result.failure.title}`
      : result.output.length > 0
        ? `Executed successfully, ${result.output.length} output(s) returned`
        : 'Executed successfully (no output captured)'
  } finally {
    if (!keepProgram) {
      // 清理失败如实记录（cleanupWarnings），不重试删除（UNKNOWN_OUTCOME
      // 不回放语义）；清理成功才置 cleanedUp=true。清理异常不得吞掉主流程
      // 的原始异常——这里只捕获清理自身的错误。
      try {
        await cleanupOnce(h, objectURL)
        result.cleanedUp = true
      } catch (cleanupError) {
        result.cleanupWarnings.push(
          `cleanup DELETE for temporary program ${programName} failed: ${String(cleanupError).slice(0, 200)}`
        )
      }
    }
  }
  return result
}

/** 对象清理（锁 → DELETE 一次，失败不重试；对齐 VSP cleanup 语义）。 */
async function cleanupOnce(h: ExecuteAbapHttp, objectURL: string): Promise<void> {
  const lock = await h.lock(objectURL, 'MODIFY')
  const lockRecord = lock as { LOCK_HANDLE?: string; lockHandle?: string }
  const handle = String(lockRecord.LOCK_HANDLE ?? lockRecord.lockHandle ?? '')
  if (!handle) throw new Error('could not lock the temporary program for cleanup')
  await h.deleteObject(objectURL, handle, '')
}

/* ==========================================================================
 * 客户端绑定（供 MCP handler 接线的注入点）
 * ==========================================================================
 * ExecuteAbapHttp 的全部方法都映射到 AdtClient 既有公开 ADT 能力
 * （objectcreator.createObject / objectcontents.lock·unLock·setObjectSource /
 * activate.activate / api/delete.deleteObject / api/unittest.runUnitTest）。
 * 注意：lock/setObjectSource 内部 ValidateStateful——本链必须绑定写域
 * stateful 主客户端（this.adtClient.httpClient），与 runClass/unitTestRun 同面。
 */

export interface ExecuteAbapClient {
  /** 受控执行用户 ABAP 片段（临时程序包装 + ABAP Unit 单次运行）。 */
  executeAbap(code: string, opts?: ExecuteAbapOptions): Promise<ExecuteAbapResult>
}

/**
 * 把 AdtHTTP 会话绑定成 ExecuteAbapClient。接线方式：
 * createExecuteAbapClient(this.adtClient.httpClient)——必须用写域 stateful
 * 主会话（锁与源码写入是 stateful 专属操作），不得绑读域 stateless clone。
 */
export function createExecuteAbapClient(h: AdtHTTP): ExecuteAbapClient {
  const http: ExecuteAbapHttp = {
    create: options => createObject(h, options),
    lock: (objectUrl, accessMode) => lock(h, objectUrl, accessMode),
    updateSource: (objectSourceUrl, source, lockHandle, transport) =>
      setObjectSource(h, objectSourceUrl, source, lockHandle, transport || undefined),
    unlock: (objectUrl, lockHandle) => unLock(h, objectUrl, lockHandle),
    activate: (objectUrl, objectName) => activate(h, objectName, objectUrl),
    runUnitTest: (url, flags) => runUnitTest(h, url, flags),
    deleteObject: (objectUrl, lockHandle, transport) =>
      deleteObject(h, objectUrl, lockHandle, transport || undefined)
  }
  return { executeAbap: (code, opts) => executeAbapViaUnitTest(http, code, opts) }
}
